// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quota.Aggregator.Context;

#nullable disable

namespace Quota.Aggregator.Migrations
{
    [DbContext(typeof(AggregatorDbContext))]
    partial class AggregatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quota.Aggregator.Models.UserQuote", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.HasKey("Username", "QuoteId");

                    b.ToTable("UserQuotes");
                });
#pragma warning restore 612, 618
        }
    }
}
