version: '3.4'

services:
  quota-userdb:
    image: postgres

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

volumes:
  postgres_data: