version: '3.4'

services:

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  quota.pgadmin:
    container_name: quota.pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  quota.aggregatordb:
    container_name: quota.aggregatordb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=QuotaAggregatorDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_aggregator_data:/var/lib/postgresql/data/


  quota.userdb:
    container_name: quota.userdb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=QuotaUserDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data/

  quota.quotedb:
    container_name: quota.quotedb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=QuotaQuoteDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_quote_data:/var/lib/postgresql/data/

  user.api:
    container_name: quota.user.api
    depends_on:
      - quota.userdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=quota.userdb;Port=5432;Database=QuotaUserDb;User Id=admin;Password=admin1234;"
    ports:
      - "8000:80"
