version: '3.4'

services:

  quota.pgadmin:
    image: dpage/pgadmin4

  quota.userdb:
    image: postgres

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data: