version: '3.4'

services:

  quota.pgadmin:
    image: dpage/pgadmin4

  rabbitmq:
    image: rabbitmq:3-management-alpine


  quota.aggregatordb:
    image: postgres

  quota.userdb:
    image: postgres

  quota.quotedb:
    image: postgres

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

volumes:
  postgres_user_data:
  postgres_quote_data:
  postgres_aggregator_data:
  pgadmin_data: